### ISSUE TITLE
Double output on the console

### ISSUE THREAD

**Issue by Faryzal2020** [chirs241097/jline4mcdsrv#23] opened 2024-03-18 10:12 UTC
I've just installed a new modpack on my server (Prominence II) with this mod and the output on the console become doubled, but normal in the logs.
In my previous installed modpack (Create Optimized) the mod works fine.
I've asked about this in the discord channel for Prominence II but the dev just redirects me to their wiki, which does not contain anything that would help me.

![image](https://github.com/chirs241097/jline4mcdsrv/assets/8612170/b92e14cb-9c7c-43f1-a04c-5281adc34b94)

**Comment by Fourmisain** [comment] 2024-03-18 17:47
I think I remember having this issue in relation to Not Enough Crashes and potentially other mods which try to deobfuscate stack traces - I see `StackDeobfuscatorFabric-1.4.1+03a1fe4` in the mod list, maybe that's what's causing it?

Yeah, looking at the code, it [changes the logger configuration](https://github.com/booky10/StackDeobfuscator/blob/64f941a15d55c835d85e33334672b6bb438fc94a/common/src/main/java/dev/booky/stackdeobf/util/RemappingRewritePolicy.java#L32-L44) similar to how NEC did.
Weird, I thought I tried a deobfuscate mod some while ago and don't remember any issues.

(Btw, how do you get that modpack running on a server? I used the Fabric installer to create a blank Fabric 1.20.1 server, downloaded the pack via the CurseForge app and copied the stuff over, but it fails due to `ClassNotFoundException: org.apache.commons.compress.archivers.ArchiveException`. Looks like the Fabric installer isn't installing the `commons-compress` library for some reason...?)

Simplest fix should be to uninstall that mod, until I add compatibility code to jline4mcdsrv.

**Comment by Fourmisain** [comment] 2024-03-18 19:59
Should be fixed!
New version 0.5.0 is up!

**Closed as completed by Fourmisain** 2024-03-18 19:59 UTC

**Comment by Faryzal2020** [comment] 2024-03-18 20:19
> I think I remember having this issue in relation to Not Enough Crashes and potentially other mods which try to deobfuscate stack traces - I see `StackDeobfuscatorFabric-1.4.1+03a1fe4` in the mod list, maybe that's what's causing it?
> 
> Yeah, looking at the code, it [changes the logger configuration](https://github.com/booky10/StackDeobfuscator/blob/64f941a15d55c835d85e33334672b6bb438fc94a/common/src/main/java/dev/booky/stackdeobf/util/RemappingRewritePolicy.java#L32-L44) similar to how NEC did. Weird, I thought I tried a deobfuscate mod some while ago and don't remember any issues.
> 
> (Btw, how do you get that modpack running on a server? I used the Fabric installer to create a blank Fabric 1.20.1 server, downloaded the pack via the CurseForge app and copied the stuff over, but it fails due to `ClassNotFoundException: org.apache.commons.compress.archivers.ArchiveException`. Looks like the Fabric installer isn't installing the `commons-compress` library for some reason...?)
> 
> Simplest fix should be to uninstall that mod, until I add compatibility code to jline4mcdsrv.

thank you! i've been looking at the entire 400 modlist of the modpack and their configs for 3 hours and couldn't find the culprit.

To get the modpack running on server you need to make sure that you're using the same fabric loader version as the client, in the curseforge it says Fabric 0.14.25 so i downloaded and used the server launcher of that exact version. Try run the fabric vanilla first on the server, if works then copy over the mod files and restart.

**Comment by Fourmisain** [comment] 2024-03-18 21:40
> thank you! i've been looking at the entire 400 modlist of the modpack and their configs for 3 hours and couldn't find the culprit.

Haha! Yeah, it's never obvious in large mod packs.
We had an issue in our FettLol modpack where phantoms would spawn, but they would simply never attack any player.
You could attack them and they would try to fight back for like a second, before becoming tame like a sheep again.
I tried searching through all mods' source code for anything related to "phantom" or "spawning" and the literally only thing that came close to touching phantoms was Architectury, which has an API that allows to control phantom spawns (turning them on/off under certain conditions), which was simply not it.
So I tried replicating the issue locally by setting up my own server with the modpack, waited for phantoms to spawn aaaand... they attacked me... like they are supposed to. Welp.
We never found out what the issue was, but it was miraculously fixed after a server reset.
(It was probably **some** difference in mod versions or datapacks on the server vs my own setup, but we'll never know.)

Anyway, here's a tip:
If you have a **reproducable** issue you're stuck alone with, you can always try the route of halfing your modlist and seeing if the issue still persists.
If yes, you know the issue is in the active half.
If not, it's in the other half.
Half that broken half repeatedly until you find your culprit.

That method works well for finding most issues / mod conflicts. It's just a bit annoying to do when mods have dependencies.

> To get the modpack running on server you need to make sure that you're using the same fabric loader version as the client, in the curseforge it says Fabric 0.14.25 so i downloaded and used the server launcher of that exact version. Try run the fabric vanilla first on the server, if works then copy over the mod files and restart.

That's what I tried!
Used Fabric Installer 1.0.0 to install Minecraft server version 1.20.1, loader version 0.14.25.
Made sure to run both the server and the client once, both worked.
Copied the Prominence II [RPG] stuff over, `ClassNotFoundException`.

I just tried again and... actually got something different this time!
EuphoriaPatcher throws `NoClassDefFoundError: net/minecraft/client/gui/screen/Screen`, i.e. the mod is trying to access client code, which obviously doesn't exist on the server.
That was actually [fixed upstream](https://github.com/EuphoriaPatches/EuphoriaPatcher/commit/ac943540b40f2d9104f72f5eb726cf82746594a0) but not released it looks like.
Easy fix, just delete that from the server mod folder.

Now it's the next mod, `ktnilcks` aka ItemLocks, which does the same thing... 😅
Remove that and... now the server runs!

Okay, I thought the issue was maybe in fabric installer, it's not. That's all I wanted to know.
So if you run into this issue as well, now you know too to remove those 2 mods from the server!
